### ISSUE TITLE
pter adds CRLF line terminators on Linux

### ISSUE THREAD

**Issue by maxigaz** [vonshednob/pter#11]
Steps to reproduce (tested under Manjaro Linux with pter 3.0.0):

1. Create a new `todo.txt` in Vim or Neovim, add a few tasks, and exit the editor.
1. Run `file todo.txt`. It should show the following output:

   ```
   todo.txt: Unicode text, UTF-8 text
   ```
1. Open `todo.txt` in pter, make some edits (for example, mark a task as done).
1. Run `file todo.txt` again. Now it shows the following:

   ```
   todo.txt: Unicode text, UTF-8 text, with CRLF line terminators
   ```

Neovim also shows this change, by running `:set ff` or looking at luabar with the default configuration.

While I'm not seeing any negative effects of this right now, a few weeks ago, when I opened one of my `todo.txt` files in Neovim, I noticed that it contained `^M` at the end of every line. Then I realised it had been edited with pter. I think that was somehow related to this issue.

**Comment by vonshednob** [comment]
Please try to update pytodotxt through `pip install -U pytodotxt`. There has been [a fix recently](https://github.com/vonshednob/pytodotxt/issues/3) that addresses that problem.

Let me know if that does the trick!

**Comment by maxigaz** [comment]
Yes, updating that package fixes the issue. Thank you!
