### ISSUE TITLE
More important/Less important not working?

### ISSUE THREAD

**Issue by pglaz** [vonshednob/pter#13]
Hello!

Let's say that I have the following todotxt file:

```
(A) 2022-01-01 Call Mom @Phone +Family
(A) 2022-01-02 Schedule annual checkup +Health
(B) 2022-01-03 Outline chapter 5 +Novel @Computer
(C) 2022-01-04 Add cover sheets @Office +TPSReports
```

(which is [the sample todo.txt](http://todotxt.org/todo.txt) but with creation date added)

If I try to see tasks more important than C I access the search field, type:

`mi:C`

and press Enter. But it shows no tasks. Am I using it wrong or is there a problem? Thanks!

**Comment by vonshednob** [comment]
Hm, I agree with you, the behaviour you describe (and I can confirm that I see it, too) is not as intended. I.e. it's a bug alright!

Thanks for pointing it out, I'll take care of it!

**Comment by vonshednob** [comment]
Alrighty, that was awkward. I'm sure it used to work at some point, but by now it was hopelessly broken.

It didn't support the promised relative dates either (like `duebefore:+1w`).

But now, with version 3.1.1 it's fixed. `pip install -U pter` will get you up to date.

I also added a bunch of new unit tests to make sure it doesn't break again that quickly.

Thanks again for pointing it out and sorry for the inconvenience!
