### ISSUE TITLE
Easily set priority for selected task

### ISSUE THREAD

**Issue by jerseyblue** [vonshednob/pter#16]
I frequently organize my list by changing the priority of tasks. Perhaps you can map keys to add/remove, increase or decrease the priority of a task. E.g., shift-A makes the task priority A. Overall I really like your tool. I've been a long time user of the Todo format for tracking tasks.

**Comment by vonshednob** [comment]
Glad you like it :)

I very much like the idea of being able to increase/decrease the priority of a task by shortcut!
So far I had only considered to set the priority directly through shortcuts, but never implemented it. This is a good motivation.

**Comment by jerseyblue** [comment]
Happy to help in any way. My coding chops are a bit rusty but I can test etc.

**Comment by vonshednob** [comment]
pter’s code is also not the cleanest thing to work with, I’m afraid. As usual, needs clean-up anyway *sigh*

I’ll update this issue when there are things to test!

**Comment by vonshednob** [comment]
Righty, version 3.3.0 should solve this for you!

There are a few more shortcuts (and functions) to

 * increase priority (`+`, `prio-up`)
 * decrease priority (`-`, `prio-down`)
 * remove priority (`=`, `prio-none`)
 * set priority to `A` (`A`, `prio-a`)
 * set priority to `B` (`B`, `prio-a`)
 * set priority to `C` (`C`, `prio-a`)
 * set priority to `D` (`D`, `prio-a`)

But all of that should be documented, as usual, in the man page for `pter`.

Let me know if this is what you had in mind and/or if something else is wrong or missing!

**Comment by nickfun** [comment]
Ha, I was looking around for how to do this as well, nice to see it get worked on. I'm looking forward to the release of 3.3.0 :-) I don't see a branch with it, perhaps you only push to github on full release?

**Comment by vonshednob** [comment]
Whoops! Sorry for not communicating clearly! Version [3.3.0](https://pypi.org/project/pter/) is already released! Run

    pip3 -U pter

to update!

You can also run `pter --check-for-updates` to, well, check whether there are updates :)

@nickfun, thanks a lot for being ready to jump in! :+1: However, I should point out that the version of pter on github is only updated every now and then. The code is pypi is the leading source and the "truth" is sitting on my private gitolite server.
I'm more than happy to receive patches though! (pull requests will work, too, for now, but are causing more work :sweat_smile: )

**Comment by nickfun** [comment]
Oh, thanks for clarifying. I'm used to github being _the place_ for everything. I'm on 3.3.0 now and happy, thanks for this cool project 🚀

**Comment by vonshednob** [comment]
Glad you like it and thanks again for offering help! It's really appreciated!

**Comment by jerseyblue** [comment]
Thanks for being so responsive and adding this functionality! Works great.
