### ISSUE TITLE
An error when trying to load the manual

### ISSUE THREAD

**Issue by jason-mehmel** [vonshednob/pter#17]
Hey there!

Loving pter. I noticed this error when I hit the manual key while using the terminal version. It's also happening in the Qt version.

*Access to the file was denied

The file at /home/jason/.local/lib/python3.10/site-packages/pter/docs/pter.html is not readable.
It may have been removed, moved, or file permissions may be preventing access.*

There is a .html file there, but I can't access it either just by trying to open it with a browser.

**Comment by vonshednob** [comment]
Ahoy!

That’s a really strange one! I can’t reproduce it on my machine, so I will have to ask a lot of stupid questions (sorry for that). Let’s start with these:

- What OS are you running?
- What browser does it start? And is that your preferred browser?
- What does `ls -l /home/jason/.local/lib/python3.10/site-packages/pter/docs/pter.html` say?
- If you have a blank text file at `/home/jason/blank.txt` and you try to open it in your browser (`file:///home/jason/blank.txt`), does that work?

**Comment by vonshednob** [comment]
It's been a year, so I'll close this. If the issue should pop up again, feel free to reopen the issue!
