### ISSUE TITLE
corresponding to home `~` in windows is?

### ISSUE THREAD

**Issue by yashpalgoyal1304** [vonshednob/pter#22]
What does `~` or the home directory translates to in windows?

> `The configuration file's default location is at ~/.config/pter/pter.conf.`

**Update:** 'ts `%USERPROFILE%` - go to https://github.com/vonshednob/pter/issues/22#issuecomment-1333838365

coming here from:
* https://github.com/vonshednob/pter
<-- http://todotxt.org
<-- https://alternativeto.net/software/todotxt/about/
<-- https://alternativeto.net/browse/search/?q=todo

<details>

<summary>old description</summary>

it always kills me to decode this dreaded `~` in the location - please share one typical example of where this can be in windows - we don't have linux like dir structure here 😭 . we are `home`-less

sorry for such a tone, i am just tired of so many tasks at hand

</details>

**Comment by vonshednob** [comment]
Oh, sorry for the confusion!

You’re right, the abbreviation `~` is not very clearly explained in the documentation.

On Windows (tried on Win10 just now) it is `C:\Users\<your username>\.config\pter\pter.conf`.

But, you can also place it in a different location, buy then you’ll have to start pter (or qpter) with `-c <location of your config file>`.

I hope this helps!

Also: thanks a lot for indicating how you came here :)

**Comment by yashpalgoyal1304** [comment]
so, per the manual, `%USERPROFILE%/.config/pter/pter.conf` should open the directory, but, i found that there's no `pter` folder in the .config, so, should i create that??

**Comment by vonshednob** [comment]
Yes, if you want to override the defaults, you will have to create the file yourself!

**Comment by yashpalgoyal1304** [comment]
okay :+1:
