### ISSUE TITLE
Context aware new item

### ISSUE THREAD

**Issue by lrustand** [vonshednob/pter#26]
It would be very nice if new item was context aware, so that if I am currently viewing a +project or @context through search, then the new item is automatically added to this context.

**Comment by lrustand** [comment]
Oh wow, this one is also possible through configuration settings. I guess I should really read the manual before posting issues...

 Sorry, closing as solved!

**Comment by vonshednob** [comment]
Haha, I completely missed these issues :sweat_smile:

Glad the problems could be fixed without intervention :grin:
