### ISSUE TITLE
Brewing

### ISSUE THREAD

**Issue by BuonOmo** [vonshednob/pter#28]
FYI: https://github.com/Homebrew/homebrew-core/pull/146124

**Comment by vonshednob** [comment]
Wow, thanks!

**Comment by vonshednob** [comment]
Oh, please note that there’s an issue with pter on Mac atm that’s being investigated, but unsolved -> [issue on codeberg](https://codeberg.org/vonshednob/pter/issues/12)

**Comment by BuonOmo** [comment]
It's all good. If you want to `brew bump` it yourself when a new version is coming for sure do it. But we'll when it happens and when someone will need it they'll do it !

And about the bug, maybe it could be mentioned in caveats when installing if you think the bug itself won't be solved soon.

**Comment by BuonOmo** [comment]
Oh one thing though, I only shipped the TUI version. One might want to ship the qt version as well. I chose not to to avoid loading too much stuff, might be good as a separate formula (or even a cask as it is a GUI).

**Comment by vonshednob** [comment]
> Oh one thing though, I only shipped the TUI version. […] I chose not to to avoid loading too much stuff, might be good as a separate formula (or even a cask as it is a GUI).

Excellent choice! I regret the decision back when to package pter and qpter in the same deliverable.

**Comment by BuonOmo** [comment]
By looking again at the shipped package, it detected qpter and installed it. I don't think this only is worth a PR though
