### ISSUE TITLE
Export time tracking to a csv

### ISSUE THREAD

**Issue by luismidelgado** [vonshednob/pter#3]
Is it possible to export the time tracking of the tasks to a csv?

Thanks for this great program

**Comment by vonshednob** [comment]
Glad you like the program!

Should be easy enough to hack a script that could export the tracked time to a csv file :thinking:
Feels like an extra program though, to be honest, not so much a built-in functionality.

I’ll have a look at it!

**Comment by vonshednob** [comment]
Alrighty, it’s fairly complex actually" what would you want to export? Just the tasks and the used time? Or group them by project/context? Accumulate the time when grouping? Over all time? Or just last week? Consider time between creating the task vs. when closing the task?

All that reminded me that the analysis of todo.txt files is already solved, thanks to @danielk333! Check out https://github.com/danielk333/pter_analysis

If this does not quite help you, please reopen this issue!
