### ISSUE TITLE
Support Python 3.12

### ISSUE THREAD

**Issue by chenrui333** [vonshednob/pter#30]
While trying to build the latest release, 3.9.0 against py3.12, we found some issue:

```
/opt/homebrew/Cellar/pter/3.9.0/libexec/lib/python3.12/site-packages/pter/utils.py:21: SyntaxWarning: invalid escape sequence '\s'
  EMPTY_FIELD_RE = re.compile('([a-z]+[:])(?:\s|$)')
To start pter you must provide at least one todo.txt file. See --help for more information.
```

relates to https://github.com/Homebrew/homebrew-core/pull/151150

**Comment by vonshednob** [comment]
I'll get right on it!

**Comment by vonshednob** [comment]
Alright, fixed in [version 3.10.0](https://codeberg.org/vonshednob/pter/src/tag/v3.10.0) (also on [pypi](https://pypi.org/project/pter/)).

Thanks for letting me know about this!

**Comment by chenrui333** [comment]
still repro with 3.10.0

- `virtualenv -p python3.12 . && source bin/activate`
- `pip install pter`

**Comment by vonshednob** [comment]
That’s strange. I cannot reproduce that issue:

```bash
# pter --version
pter 3.10.0
# python --version
Python 3.12.0
# pter todo.txt
```

Is it the same error message, about the `SyntaxWarning`?

**Comment by dtrodrigues** [comment]
There's a `curses` issue that should work on Python 3.12 on macOS after https://github.com/python/cpython/issues/111460 is resolved.

**Comment by vonshednob** [comment]
Thank you @dtrodrigues for pointing that out!

**Comment by chenrui333** [comment]
seems working fine now with 3.11.4 release, https://github.com/Homebrew/homebrew-core/pull/157699. Closing.
