### ISSUE TITLE
Improvements to todo item editing

### ISSUE THREAD

**Issue by andrei-a-papou** [vonshednob/pter#36]
I'd like to propose the following improvements to editing a todo:

1. By way of analogy to the `del-to-bol` command, add a `del-to-eol` command. It could have a default binding of `^K` -- a-la Emacs/Midnight Commander.
2. Would it be possible to implement `Ctrl` + arrow keys navigation? A user holds down `Ctrl` and then the left/right arrow keys move a whole word at a time. When editing a longer todo, this allows moving around much more efficiently :) 
3. In the same way, would it be possible to add `del-word-right` and `del-word-left` (perhaps bound to `Ctrl + Delete` and `Ctrl + Backspace` by default) to delete one word at a time?

**Comment by vonshednob** [comment]
Perfect requests! Yes, these are possible to implement, but I was too lazy and was hoping for someone to come around and complain :grinning:

**Comment by andrei-a-papou** [comment]
Being able to use Ctrl-based bindings when editing todos is very important to me since I'm currently grooming a large todo file. So I made a patch myself :) The code is probably ugly in places if only because I know next to nothing about curses. So I'll most certainly appreciate it if you could take a look.

Things seem to work fine after a half day of usage, but give me a couple days to test it more thoroughly in the trenches and I'll post the patches, is that OK?

**Comment by vonshednob** [comment]
By all means! Forking and patching is what open source is good for, after all :grin:

**Comment by andrei-a-papou** [comment]
I've tested my patches for a couple of days, and they seem to be stable. So here you go:

[80-ctrl-key-functions-1.diff.gz](https://github.com/vonshednob/pter/files/14322601/80-ctrl-key-functions-1.diff.gz)
[80-ctrl-key-functions-2.diff.gz](https://github.com/vonshednob/pter/files/14322603/80-ctrl-key-functions-2.diff.gz)
[90-ctrl-key-combos.diff.gz](https://github.com/vonshednob/pter/files/14322604/90-ctrl-key-combos.diff.gz)

I'm not 100% sure the detection of Ctrl-based combinations will work on every machine (I detect values of `524`, `550` and `565`), so I'd be curious about your experience. Anyway, key combinations in `curses`-based apps can be tricky due to various terminals and environments used.

Also, I've redefined `^H` for `Ctrl + Backspace` and not a plain `Backspace`.  This is a bit non-standard, but the user can always map <ctrl_backspace> to `del-left` to make both `^H` and  `^?` act as Backspace.

**Comment by vonshednob** [comment]
Yeah, the keymap compatibility due to the various terminals has caused other issues, too. I have the nagging feeling that these types of issues will accumulate to a degree that might require a change of the backend… well, that’s for the future.

I’ll merge your changes with the next release! Thanks a lot!

**Comment by vonshednob** [comment]
Aaaand merged! Soon I'm through all pending issues and then I'll release.

I might add the configuration option `word-boundary-characters` or `word-delimiters` or something.

**Comment by andrei-a-papou** [comment]
> Aaaand merged! Soon I'm through all pending issues and then I'll release.

Can't wait! :)

> I might add the configuration option `word-boundary-characters` or `word-delimiters` or something.

Yes!


P. S. Is this a good time to also take a look at #52 and possibly merge it?

**Comment by vonshednob** [comment]
Absolutely! I intend to get all the open issues into the next release.

**Comment by andrei-a-papou** [comment]
Alright, but releasing might take a while if I keep sending you patches :) I'll stop for now :)

**Comment by vonshednob** [comment]
So here we go -- until the end of this weekend I'll still assign new issues to the version 3.16 milestone but every subsequent new issue will have to wait longer. This'll do the trick to get a release out, I'm sure :grin:
