### ISSUE TITLE
Search for only hidden and/or postponed tasks?

### ISSUE THREAD

**Issue by andrei-a-papou** [vonshednob/pter#38]
I am playing around with the search feature/saved searches and generally speaking I love it! 

However, I've read the docs and there doesn't seem to be a way to show _only_ hidden tasks or _only_ ticklers. Or perhaps I haven't thought of a way? Would appreciate a pointer then :) 

Like others, I use hidden tasks to store projects/contexts and some other tech info. I can show hidden tasks via `h:yes`, but this also shows all other tasks. Since I have ~150 todos, finding the hidden ones is a challenge. Same goes for  ticklers: sometimes I need to quickly look at all the postponed tasks and them only.  Is it possible?

**Comment by vonshednob** [comment]
Hm, interesting. I agree this is a case that I had not considered and that’s currently not at all supported.

Right now the search treats searches for `h:` and `t:` as logically "or" connected (almost all other search terms are "and" connected).

Short of requiring the user to actually provide the `and`s and `or`s manually (this would be terrible! it comes with `(` grouping `)`), there has to be a new search term that expresses the "and" connection to the rest of the search for `t:` and `h:` fields.

Two minutes of thinking yielded only crappy solutions, like having a `T:` and `H:` search term that is the same as `t:` and `h:`, but are "stronger" in the sense that a task *must* have these. Any better idea is really appreciated!

**Comment by andrei-a-papou** [comment]
I thought about `H:` and `T:` myself but frankly I wouldn't got there. I think it fosters further inconsistencies: special search keywords like `due:` are case-insensitive and introducing a case-sensitive one feels confusing. 

How about this: make `h:` and `t:` searches _consistently_ use AND between terms. Then you could search for `hidden:yes` to only show the hidden tasks. Additionally, introduce the `any` value, so searching for `hidden:any` or `h:any` shows all tasks, including hidden ones.

Docs would need to be updated to reflect the change and I'll be happy to help with that. There are some typos and possible improvements in the docs that I could fix, I'll send a patch for you to consider, hopefully this weekend.

**Comment by vonshednob** [comment]
That's a really good idea, I like it! Especially because it'll make things more consistent. I'll put it in the next bigger release.

**Comment by andrei-a-papou** [comment]
I'll be happy to test it!

**Comment by vonshednob** [comment]
The `hidden:any` search is already implemented (see [here](https://codeberg.org/vonshednob/pter/commit/0f1a4bcfd045f0123be2604d75e4714a396740a9)), `t:` is coming soon™.

**Comment by andrei-a-papou** [comment]
Just tested, seems to work great, thank you! I can finally hunt down my hidden tasks :)

**Comment by vonshednob** [comment]
Alright, these are in now with [this commit](https://codeberg.org/vonshednob/pter/commit/129743df823d7500df201e44615b2a62e2741650)

**Comment by andrei-a-papou** [comment]
Hm... `done:` and `done:any` work the same way, so do `t:` and `t:any`. But `h:` functions as `h:yes`, not as `h:any`.

**Comment by vonshednob** [comment]
And that was documented and tested accordingly. Still inconsistent though :sweat_smile:, so I fixed it in [db298aa0](https://codeberg.org/vonshednob/pter/commit/db298aa07e43460755bca87b3282215f535b5c60)

**Comment by andrei-a-papou** [comment]
Thank you! Seems to work like a charm.
