### ISSUE TITLE
Patch to print version in statusbar

### ISSUE THREAD

**Issue by andrei-a-papou** [vonshednob/pter#40]
Since I have to run pter in a Docker container, I can't easily run pter -v (the container is deliberately set up a certain way). I also sometimes jump between versions as there could be a serious bug or a regression in one of them. 

Anyway, I thought putting version in the welcome message would be an easy fix. Here's a small patch I made -- take it or leave it, but I guess it doesn't hurt and it does provide some useful info to users. 

I would certainly appreciate a merge so I won't have to maintain the patch on my end :) 

[95-version-statusbar.diff.gz](https://github.com/vonshednob/pter/files/14284986/95-version-statusbar.diff.gz)

**Comment by vonshednob** [comment]
Darn, I missed this before I pushed out 3.15.2 just now. Sorry! :sweat_smile: Next version will have it in!

**Comment by vonshednob** [comment]
It'll be in the next release, but you can preview it from the stuff on codeberg.
