### ISSUE TITLE
Consistency issue when searching for done: and due: 

### ISSUE THREAD

**Issue by andrei-a-papou** [vonshednob/pter#44]
When searching, there seems to be a UX consistency issue between `done:` and `due:`. 

Done searches:
1. `done:yes` -- works
2. `done:y` -- works
3. `done:no` -- works
4. `done:n` -- works

Due date searches:
1. `due:yes` -- works
2. `due:y` -- works
3. `due:no` -- works
4. `due:n` -- does NOT work

In addition, there's a difference between `due:` and `done:` (when no value is specified). The former works as `due:today` while the latter works as `done:any` (no such value has been implemented for now). 

Personally, I would make the "empty value" behavior explicit. When no value is specified, the behavior is not clear (at least when enough tasks match the search).

Perhaps the "any" value should be implemented here as well, as discussed in #38? That way:
1. `due:` and `done:`  would not match anything because no value has been specified
2. `due:any`  would show tasks that have a non-empty `due:` tag
3. `done:any`  would show all tasks (same as `done:` does now, but explicitly to the user)

@vonshednob What are your thoughts?

**Comment by andrei-a-papou** [comment]
> Hm, I was thinking about the any value and I think it should probably be the explicit version of just the tag, i.e. due: being the same as due:any, the latter just being explicit.

Sounds good to me, as long as it's consistent with other shorthand/empty-value versions, like `h:` and `t:`

**Comment by vonshednob** [comment]
And done! [See here](https://codeberg.org/vonshednob/pter/commit/129743df823d7500df201e44615b2a62e2741650)

**Comment by andrei-a-papou** [comment]
OK, `done:y`, `done:n`, `done:any`, `done:` work fine.
