### ISSUE TITLE
Patch to capitalize days of week in relative dates

### ISSUE THREAD

**Issue by andrei-a-papou** [vonshednob/pter#45]
English days of week must be capitalized, so here goes :) 
[97-capitalize-dow.diff.gz](https://github.com/vonshednob/pter/files/14322590/97-capitalize-dow.diff.gz)

**Comment by vonshednob** [comment]
hehe, good point.

**Comment by vonshednob** [comment]
I'm using github's `noreply.github.com` domain as the email address for your commits; hope that's okay. See [here](https://codeberg.org/vonshednob/pter/commit/9853c529d1beb7aebfbc898a101ab0d0aa0e2a55)
