### ISSUE TITLE
A standalone "+" character is offered as a completion item

### ISSUE THREAD

**Issue by andrei-a-papou** [vonshednob/pter#46]
Here's a minor bug: when you have a todo like `Implement Ctrl + Backspace`, pter picks up the plus character as a project and offers it as an autocomplete suggestion. This doesn't happen for the "Select project" dialog though.

Same thing for a standalone '@' char.

**Comment by andrei-a-papou** [comment]
Here's a quick and dirty fix, couldn't think of a better one :)

[98-fix-completion.diff.gz](https://github.com/vonshednob/pter/files/14323510/98-fix-completion.diff.gz)

**Comment by vonshednob** [comment]
There is exactly one quick and dirty fix I can think of, let’s see if we thought the same :grin:

**Comment by vonshednob** [comment]
Almost the same. Unfortunately the patch was also triggering crashes when there was no `+` or `@` when completing a `+` or `@`. Anyway, it's fixed with [this commit](https://codeberg.org/vonshednob/pter/commit/a43f3d8207a9766bd26de5fa635e07cdcfa0e533)!

**Comment by andrei-a-papou** [comment]
Seems to work great!
