### ISSUE TITLE
Patch to improve item highlighting in project/context selectors

### ISSUE THREAD

**Issue by andrei-a-papou** [vonshednob/pter#47]
It's a minor UX thing, but it would be nice, IMO, if item highlighting filled the whole Selector width, like it does for completion. 

Here's a patch:
[98-fix-highlghting-in-project-context-selectors.diff.gz](https://github.com/vonshednob/pter/files/14328252/98-fix-highlghting-in-project-context-selectors.diff.gz)

In addition, would it be possible not to truncate project and context selector titles? Maybe a minimal title/dialog width can be implemented to make sure short titles like "Select project" and "Select context" do not get ellipsized?

**Comment by andrei-a-papou** [comment]
Without minimal title width, we can get a situation like this:

![image](https://github.com/vonshednob/pter/assets/30468319/22a546b5-725c-44fb-9677-48acf7f23d1b)

:)

**Comment by vonshednob** [comment]
Patch is merged and the title is no longer cut off!

**Comment by andrei-a-papou** [comment]
Nice!
