### ISSUE TITLE
Distraction-free task editing/creation

### ISSUE THREAD

**Issue by andrei-a-papou** [vonshednob/pter#49]
I've been using pter heavily for some time and I generally love it. Especially with [improved line editing](#36), I can now have super-fast and efficient keyboard-driven workflows. And I haven't even started using automatic templates or hooks :)

So kudos for such a great tool, I mean it.

There are some minor UX hiccups [here](#46) and [there](#47), but nothing that can't be fixed or improved over time.

One annoying UX issue that I have right now is when "New task" and "Edit task" dialogs are painted on top of a _fully-populated_ task list. The task list is not blurred or dimmed in any way, the input dialog sort of blends with the task list, which makes it relatively hard to read. IMO, it would be much better to either dim the task list, or clear it completely and then repaint it on input dialog close.

Can this be implemented (perhaps as an option, like `distraction-free-editing`)?

**Comment by vonshednob** [comment]
Added a `reduce-distraction` option that hides the tasks when there's another dialog open in general. Let me know if this is what you had in mind!

**Comment by andrei-a-papou** [comment]
Look awesome, thanks a bunch!
