### ISSUE TITLE
Patch for help screen

### ISSUE THREAD

**Issue by andrei-a-papou** [vonshednob/pter#50]
I have unbound the "open URL" command and now the "Other" section on the Help screen is empty. Here's a quick patch to hide this section if no relevant commands have keys bound to them:

[99-show-help-section-conditionally.diff.gz](https://github.com/vonshednob/pter/files/14348309/99-show-help-section-conditionally.diff.gz)

**Comment by vonshednob** [comment]
Thank you so much for all your work! I'll try to bundle all of the patches for release this week!

**Comment by vonshednob** [comment]
You are right, empty sections were silly.

**Comment by andrei-a-papou** [comment]
Thanks for making it work for all the other sections!
