### ISSUE TITLE
Mouse-wheel scrolling broken after editing a task externally

### ISSUE THREAD

**Issue by andrei-a-papou** [vonshednob/pter#51]
To reproduce:

1. have several tasks on the list
2. use mouse wheel to scroll up and down and notice how scrolling stops at window boundaries 
3. edit a task in external editor (nano)
4. try scrolling now -- and the screen will scroll back beyond window boundaries

Same thing happens if you view a note, for example. Tested in kitty and xfce4-terminal, so doesn't seem to be a terminal issue.

Here's a short video:
![scroll-bug](https://github.com/vonshednob/pter/assets/30468319/49d0ceec-382f-4741-b7e2-203c40591973)

**Comment by andrei-a-papou** [comment]
I don't think pter needs mouse scrolling, can we disable it?

**Comment by vonshednob** [comment]
pter has mouse scrolling?! That's … new to me! I have no idea what's going on there.

**Comment by andrei-a-papou** [comment]
Looks like the terminal captures scroll events and sends them to pter. Pter interprets them as up/down arrows, so yes, we have de-facto scrolling, yay :laughing: 

Problem is, after you run a command-line editor or viewer and control returns to pter, the UI is not properly reset. If you scroll on the UI, you'll see something like the GIF above :) Does it reproduce on your end?

**Comment by vonshednob** [comment]
I can reproduce the behaviour. Now only to find out how to fix it one way or the other.

It bugs me a bit that the scroll wheel makes it look like pter actually has mouse support, so I'm even considering to attempt and sabotage the initial "nice" behaviour.

What do you think?

**Comment by andrei-a-papou** [comment]
Turns out curses can process mouse events, but personally I don't need it in pter. I've tried meddling with https://docs.python.org/3/library/curses.html#curses.mousemask but to no avail.

**Comment by andrei-a-papou** [comment]
I've discovered that sending an escape reset sequence after calling an external program mostly works (I think it still failed for me at least once but I can't reproduce it now). But this is of course very ugly and unreliable, so not a real fix :(

[99-weird-scroll-buffer-bug.diff.gz](https://github.com/vonshednob/pter/files/14365563/99-weird-scroll-buffer-bug.diff.gz)

**Comment by andrei-a-papou** [comment]
I've just noticed that opening the Help screen can also trigger the bug...

**Comment by vonshednob** [comment]
Wow, thanks a lot for spending so much of your time!

**Comment by andrei-a-papou** [comment]
This is not really a fix, more like a workaround, but it "works on my machine" :) The scrolling behavior seems to have something to do with terminfo configuration.

**Comment by andrei-a-papou** [comment]
At least with the latest git HEAD, applying the above patch often causes the screen to flicker when `jump-to` action is called in task list. Updated the patch to fix this problem: 
[99-weird-scroll-buffer-bug.diff.gz](https://github.com/vonshednob/pter/files/14544071/99-weird-scroll-buffer-bug.diff.gz)

**Comment by vonshednob** [comment]
Ooof. That’s a heavy handed way to reset the terminal. I suppose the problem is very much a curses and terminal mixture. Let me know when you find a time travel device, so I can go back in time and prevent myself from using curses and go for urwid instead. :grimacing:

**Comment by andrei-a-papou** [comment]
Yeah, resetting the term is an ugly kludge. I don't know if everyone needs it. Perhaps it could be an option in the config.

**Comment by andrei-a-papou** [comment]
OK, I've been using this patch and here's the summary on my end:

1. I think resetting the term on every paint is probably an overkill. It can also cause unnecessary flickering on some events. It does for me sometimes, but this needs more testing.
2. Resetting the term **once** at startup is fine and it also kills the initial mouse scrolling. I would just do it.
3. I would reset the terminal when getting control back from external editor, viewer or Help screen.
4. Maybe we should add a `reset-term` command or just power-up the `refresh-screen` command? Could be user-configurable (`refresh-screen-resets = yes` or similar). This would give users the ability to trigger a reset manually if necessary.

What do you think?

**Comment by vonshednob** [comment]
The worst part is that this mechanism right there? It works for you. It might even work for me (btw, `Alt+left` and `Alt+right` don't work for me; I added my termname to the `if` block, but it doesn’t get there), but who the heck knows how it’ll behave for other terminals.

It’s probably worthwhile to add the additional reset mechanism to the `refresh-screen`. That function is already a horrible workaround to potential screen output corruption, so it fits right in.

And probably calling it automatically after returning from external programs that surely mess up something (view note, edit task externally; but not when calling any of the hooks) is probably a good idea and should not interrupt the user interface, because it is being passed back to pter anyway.

**Comment by vonshednob** [comment]
So here goes nothing. In [9e52380a](https://codeberg.org/vonshednob/pter/commit/9e52380a3c0d4cc9136450b504e25971c9907317) I added the `\x1bc` escape sequence to all calls that potentially trigger external terminal programs.

The issue with the help screen might persist; I couldn't reproduce that in my configuration. Let me know if that fix works for you or breaks stuff :grimacing:

**Comment by andrei-a-papou** [comment]
It seems to work OK, but yes, the Help screen messes things up. After control returns from Help screen to task list, scrolling messes up the UI :(

**Comment by andrei-a-papou** [comment]
> btw, Alt+left and Alt+right don't work for me

For me neither, but I don't think pter ever supported these? Or do you mean [Ctrl+left/right](#36)?

**Comment by vonshednob** [comment]
Indeed, I meant `Ctrl+Left/Right/Del`.

So here's a terrible hack to maybe fix the help screen: [3d24fe53](https://codeberg.org/vonshednob/pter/commit/3d24fe536048569dd3a84e07c0bf8e5e330d5eea).

If that doesn't know: what terminal are you using? I seem to remember that you are using the `TERM=xterm` work-around?

**Comment by andrei-a-papou** [comment]
> So here's a terrible hack to maybe fix the help screen

Hey, it's not so terrible :) Resetting the term on quit is much better than on every paint :)

Anyway, seems to work OK. I think if pter resets the term on start-up to kill the misleading scrolling behavior, the issue will be mostly "resolved". That, and calling `hard_reset_terminal` on `do_refresh_screen` for unforseen situations.

**Comment by andrei-a-papou** [comment]
> I seem to remember that you are using the TERM=xterm work-around?

I set TERM to `xterm-256color`, but this is to enable color support inside a Docker container. So this is unrelated to the issue under discussion.

**Comment by vonshednob** [comment]
> I think if pter resets the term on start-up to kill the misleading scrolling behavior, the issue will be mostly "resolved". That, and calling `hard_reset_terminal` on `do_refresh_screen` for unforseen situations.

Both are in now! I just feel a bit dirty :sweat_smile:

**Comment by andrei-a-papou** [comment]
`refresh-screen` works fine, but pter still allows scrolling the screen up (but not down) on startup :(

**Comment by andrei-a-papou** [comment]
Does it scroll for you on startup (before calling viewer/editor or help screen)?

**Comment by vonshednob** [comment]
With the most recent commit I don't get any reaction in pter when using the mouse. Wheel, button, pushing, or tickling. Nothing.

I also tried with `env TERM=xterm-256color pter ...` and with `kitty` (both with and without `TERM=xterm-256color`), to no avail. For me the latest update successfully breaks all mouse-based scrolling.

Regarding the update: so the latest change made it worse? Isn't that just great :unamused:

**Comment by andrei-a-papou** [comment]
> Regarding the update: so the latest change made it worse? Isn't that just great 😒

Yeah, seems that way :( However, if I reset the terminal after painting the task list, the initial scroll is killed for me:
[reset-scroll-on-startup.diff.gz](https://github.com/vonshednob/pter/files/14594137/reset-scroll-on-startup.diff.gz)

If this works fore you too, it's one less problem. The only remaining one is the Help screen situation.

**Comment by vonshednob** [comment]
That's interesting -- so when you move the reset to that position it breaks the scrolling successfully?

**Comment by andrei-a-papou** [comment]
It does. I also "fixed" the Help screen, yay. 

But I'm thinking peppering the code with multiple calls to `hard_reset_terminal` may not be the best approach. I've just discovered that the scrolling comes back when you create a new todo in distraction-free mode :(

Perhaps the original patch that reset the main screen on paint was cleaner (if that word even applies here)...

**Comment by andrei-a-papou** [comment]
> I also "fixed" the Help screen, yay.

For what it's worth:

[reset-scrolling-on-help-screen.diff.gz](https://github.com/vonshednob/pter/files/14594257/reset-scrolling-on-help-screen.diff.gz)

**Comment by vonshednob** [comment]
At this point I'm wondering whether it's really worth the efford. Sure, scrolling is weird, but it doesn't actually break the program.

It's not impossible to fix, but is the amount of work worth it?

I'm only half joking when I mention again that I'm considering replacing the backend with urwid (don't get me wrong -- it'd be a huge undertaking though).

**Comment by andrei-a-papou** [comment]
I guess it depends on the user's habits. Me, I frequently scroll, so it's annoying when the screen slides up unexpectedly :)

But if a person never scrolls in a TUI app, they might not notice the problem at all.

I've updated my local patch and have been testing it for a couple of days. I'll post it tomorrow, if you don't mind, it needs a little more testing.

If the patch works for you, I would close the issue.

**Comment by vonshednob** [comment]
I mean, it doesn't break it for me :sweat_smile: I guess that's the best at this point to hope for.

Ie. your patches are in!

**Comment by andrei-a-papou** [comment]
OK, here's a new version that seems to cover all bases with no visible side-effects. It also fixes the "New task" dialog. I've also made the reset feature configurable (enabled by default).

Can you test it and see if it works for you?

[reset-terminal.diff.gz](https://github.com/vonshednob/pter/files/14627124/reset-terminal.diff.gz)

**Comment by vonshednob** [comment]
If it's all the same to you, I'd like to set the `reset-terminal` option to `no` by default.

Other than that, it appears to work fine for me! So I'd be fine to ship it :)

**Comment by andrei-a-papou** [comment]
> If it's all the same to you, I'd like to set the reset-terminal option to no by default.

Absolutely!

> Other than that, it appears to work fine for me! So I'd be fine to ship it :)

Great! I'l keep testing and if I stumble upon a related bug, I'll send another patch!

**Comment by vonshednob** [comment]
Let's just say this is fixed for now.

**Comment by vonshednob** [comment]
It's released now! `pip update` or similar will do the trick.

Again, thank you so much for your help and patience @andrei-a-papou ! It's really appreciated!
