### ISSUE TITLE
Patch to fix caret key issues

### ISSUE THREAD

**Issue by andrei-a-papou** [vonshednob/pter#52]
Problem: unrecognized escape sequences are seen as single caret keypresses by pter, which triggers whatever command is bound to `^` and/or outputs the caret character on screen. For example, this happens if I accidentally hit an `Alt + something` keybinding. 

I propose pter should just consume those escape sequences without outputting anything. And also _actual_  carets should still be properly recognized.

Here's a patch I've used for a couple of days, seems to work fine:
[91-fix-caret-1.diff.gz](https://github.com/vonshednob/pter/files/14382036/91-fix-caret-1.diff.gz)
[91-fix-caret-2.diff.gz](https://github.com/vonshednob/pter/files/14382037/91-fix-caret-2.diff.gz)

**Comment by vonshednob** [comment]
Got your patch in
