### ISSUE TITLE
Distraction-free mode should show task list on "jump-to" action

### ISSUE THREAD

**Issue by andrei-a-papou** [vonshednob/pter#58]
When a user invokes `jump-to`, he/she actually _does_ want to keep the task list visible, but distraction-free mode hides it. Can this be adjusted?

**Comment by vonshednob** [comment]
This one is covered now.

**Comment by andrei-a-papou** [comment]
Works great, thank you!

**Comment by andrei-a-papou** [comment]
I just noticed that calling any dialog that has a numbered list (such as "Load template", "Load search", etc) and then hitting `:` to jump to an item breaks distraction-free mode.

**Comment by vonshednob** [comment]
Hm, right. That actually makes sense… try with [ab8984da](https://codeberg.org/vonshednob/pter/commit/ab8984da8cc8bb61100f7a2f219ff9e183845030)!

**Comment by andrei-a-papou** [comment]
Works now, thank you!
