### ISSUE TITLE
Add file name completion when searching

### ISSUE THREAD

**Issue by andrei-a-papou** [vonshednob/pter#62]
When using multiple todo files, pter can already filter todos by using `file:` in the search bar. It would be nice if typing `file:` would show the completion dropdown -- so the user wouldn't have to remember the exact file name.

**Comment by vonshednob** [comment]
Not a bad idea either! Although I don't think you have to provide the exact filename? Just any distinctive part should work? Like, if one file is at `documents/project1/todo.txt` and another is at `shared/work.txt`, you should be able to find all issues from the `todo.txt` by searching for `file:pro`

**Comment by andrei-a-papou** [comment]
You're right, partial matches work! It's no big deal for me with two distinctively named files, but with more files I think it'd be helpful to make things more explicit.

And by the way, I love the fact that pter can seamlessly work with multiple files. It was a fantastic idea. I've used several todo.txt apps in the past and they all can either handle one file at a time or use something like tabs, which is often awkward.

**Comment by andrei-a-papou** [comment]
Oh, this seems easy to do:
[80-filename-completion.diff.gz](https://github.com/vonshednob/pter/files/14547705/80-filename-completion.diff.gz)

**Comment by vonshednob** [comment]
Wasn't there something about a feature freeze for version 3.16? But then again life happened and I had not have a lot of time to implement all the things… so maybe, just maybe…

**Comment by andrei-a-papou** [comment]
> Oh, this seems easy to do

I spoke too soon: the completion in this case should be limited to search bar only. It doesn't make sense in "Edit task" or "New task" dialogs, for example.

How about this:
[80-filename-completion.diff.gz](https://github.com/vonshednob/pter/files/14547771/80-filename-completion.diff.gz)

**Comment by andrei-a-papou** [comment]
And here's a patch to support highlighting {file} in task list: 
[81-filename-highlighting.diff.gz](https://github.com/vonshednob/pter/files/14551951/81-filename-highlighting.diff.gz)

**Comment by vonshednob** [comment]
Added! Thanks a lot for amazing help and your time to making pter better :grinning:

**Comment by andrei-a-papou** [comment]
Sure thing!
