### ISSUE TITLE
Bug: Editor keybindings not dumped?

### ISSUE THREAD

**Issue by andrei-a-papou** [vonshednob/pter#63]
`pter -k` doesn't seem to dump editor keybindings, e.g. `select-file` is missing.  The feature was added in #56

**Comment by vonshednob** [comment]
[There](https://codeberg.org/vonshednob/pter/commit/efb28c0ec072d52d7a33f3c59579b877b9262630) we go! A few more were missing.

**Comment by andrei-a-papou** [comment]
Thanks, tested, looks good!
