### ISSUE TITLE
new qpter issue (at least on my end!)

### ISSUE THREAD

**Issue by jason-mehmel** [vonshednob/pter#67]
After trying the pipx install pter[qt] option, I'm now getting:

> Traceback (most recent call last):
>   File "/home/jason/.local/pipx/venvs/pter/lib/python3.11/site-packages/pter/qtui.py", line 1257, in update_search
>     self.searcher.parse()
>   File "/home/jason/.local/pipx/venvs/pter/lib/python3.11/site-packages/pter/searcher.py", line 322, in parse
>     self.casesensitive.can_lowercase(''.join(self.contexts | self.not_contexts)):
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'bool' object has no attribute 'can_lowercase'
> Aborted
> 

Not sure if that's something wrong with my machine or qpter.

**Comment by vonshednob** [comment]
Pretty sure it's an issue with qpter. I'll look into it!

**Comment by vonshednob** [comment]
There was a problem with qpter's dealing with case-sensitive search option 'smart'. It's fixed in 3.16.3.

Thanks again for pointing this out! Let me know if there are more problems :)

**Comment by jason-mehmel** [comment]
Thank you for jumping on these so quickly!

**Comment by vonshednob** [comment]
No problem - I hate to have these types of bugs linger.
