### ISSUE TITLE
Bug: When creating a note for a task, the folder where it is stored does not respect the general configuration and uses the name of the todo file.

### ISSUE THREAD

**Issue by eldraco** [vonshednob/pter#68]
# Description
If having my todo.txt file in `~/folder/todo.txt`, when creating a note for a task (N), and putting a name (test.txt), the file is attempted to be stored in the directory `~/folder/todo.txt/test.txt`. 
This fails because the directory does not exist.

Even if `~/.config/pter/pter.conf` has configured
```
[General]
    files = /Users/user/folder/files/
```

# Versions
- macos m1
- python 3.11.0
- pter 3.17.0

**Comment by vonshednob** [comment]
Oh, that's strange. I'll have a look at it!

**Comment by vonshednob** [comment]
So, there really is a bug (and I'm just building the 3.17.1 release to fix it), but that bugfix is not going to make it all work for you as expected.

The `files` option is used to point to your `todo.txt` file(s); but you also want to use the `notes` option to point to the folder where you want to save your notes in!

You can try this already now; once you set the `notes` option you don't run into the bug anymore :sweat_smile: 

Let me know if this works for you!

**Comment by eldraco** [comment]
oh such nice work! Thanks!
So in summary (correct me if not)
- I can use `files` to point to my `todo.txt`
- If I edit the note on a task with `E`, the text file will be created where the option `notes` points to?

If yes, I like it.

Can I `pip install`?

**Comment by vonshednob** [comment]
> So in summary (correct me if not)
>     * I can use `files` to point to my `todo.txt`
>     * If I edit the note on a task with `E`, the text file will be created where the option `notes` points to?

Yes, this is 100% correct.

You could even point to multiple notes folders like this:

```
    [General]
    notes = 
        /Users/user/folder/files/
        /Users/user/documents/other_notes/
```

pter will try and find notes that you refer to in both folders (in order) when you press `N` to edit an existing note. In case of creating a note, that note will always be saved in the first folder.

> Can I `pip install`?

Yes, both `pip install` and `pipx install` work. If you have it installed already, `pip install -U pter` will install the newest version, 3.17.1.

You can find more documentation about pter's features in the man pages, `man pter` and `man pter.config` or over at the [codeberg project page](https://codeberg.org/vonshednob/pter).

Let me know if you have questions or issues with it!

**Comment by eldraco** [comment]
Like a charm! Works perfectly now! thanks!
